### ISSUE TITLE
git remote or branch?

### ISSUE THREAD

**Issue by btmurrell** [aviaryan/VSCodeNotebook#1]
I am confused by your instructions in the git backup section:

> you will have to make your notebook a git repository and set `notebookbackup` branch to the git remote you want to backup to

this statement seems to suggest we create a branch called `notebookbackup`

then:

> ```$ git init```
```$ git remote add notebookbackup <GIT_REMOTE_URL>```

this command will create a _remote_ named `notebookbackup` -- do we create both a branch _and_ a remote?  Is something missing (or assumed left to the reader), or is there a typo?

Thanks

**Comment by aviaryan** [comment]
Yes, it is supposed to be "remote" there. This is a typo. Thanks for pointing it out.
