### ISSUE TITLE
Git backup settings.json modified after pushing to remote

### ISSUE THREAD

**Issue by begroff** [aviaryan/VSCodeNotebook#4]
When using auto git backup, I noticed that after it pushes to the git remote it then saves the last git push config in settings.json. This causes git to detect there is a new change and shows as a pending change in VS Code. Is this the intended behavior? From an editing perspective, after I do a git backup I would like to have a clean repo. Note: In the screenshot I have the git_push_interval_minutes set to 0. 

I noticed if I move this code above the push in do_git_push function in settings.py that it doesn't detect the change but probably not best to save the settings before you push in case of failure.

![image](https://user-images.githubusercontent.com/12364330/36341288-fb85a41e-13b9-11e8-946a-ec880c5fad48.png)

**Comment by aviaryan** [comment]
> I noticed if I move this code above the push in do_git_push function in settings.py that it doesn't detect the change but probably not best to save the settings before you push in case of failure.

We can use a `try...except` block around the `git add .. && .. push ..` command and then revert back in case the push failed. That should solve this issue.

Thanks for reporting. Are you willing to send a PR for this?

**Comment by begroff** [comment]
Sure! I will send a PR as soon as I can.

**Comment by aviaryan** [comment]
@begroff Send the PR to `v2` branch. I would like to roll out the next release as soon as possible.

**Comment by aviaryan** [comment]
@begroff I am sorry but I went ahead and solved this issue. This is because I will be quite occupied in the next few days and so wanted to do the release today. Prior to this, I did check your GitHub profile and you seem to have not forked the repo till now (only after which I attempted this issue).
Thanks for your cooperation. I hope you understand. 😅
